### ISSUE TITLE
Monit does not monitor ralf_uptime or poll_ralf when Ralf has an IPv6 signalling address

### ISSUE THREAD

**Issue by AME2** [Metaswitch/clearwater-monit#52] opened 2017-02-03 14:24 UTC
I was doing some testing of creating IPv6 deployment and I noticed while running `sudo monit summary` on Ralf that a couple of processes weren't monitored:

```
 ralf_uptime                   Not monitored               Program
 poll_ralf                     Not monitored               Program
```

I can't see anything relevant in either /var/log/monit.log or /var/log/syslog

[20170206155740Z.ame2-ipv6-ralf-1.ame2.ipv6.clearwater.test.gather_diags.tar.gz](https://github.com/Metaswitch/clearwater-monit/files/755188/20170206155740Z.ame2-ipv6-ralf-1.ame2.ipv6.clearwater.test.gather_diags.tar.gz)

**Comment by eleanor-merry** [comment] 2017-02-03 14:34
Could be the same as https://github.com/Metaswitch/clearwater-etcd/issues/384

**Comment by chris-elford-metaswitch** [comment] 2017-02-06 11:04
This is high priority, as it means that the system may need manual intervention to fix if it hangs.

**Comment by chris-elford-metaswitch** [comment] 2017-02-06 11:05
And the "ralf has died" alarm will never be cleared if ralf is killed.

**Comment by mirw** [comment] 2017-02-06 15:52
@AME2, do you have any more diagnostics for this (e.g. a diags dump)?  (I can't see one.)  Assuming not, I'd say this is very likely to be a duplicate of https://github.com/Metaswitch/clearwater-etcd/issues/384 - please can you look out for this happening again now that that fix is in place?

**Comment by AME2** [comment] 2017-02-06 16:03
@MIRW Thanks for the reminder, I've edited the issue to include the diagnostic package.

Yes I will keep an eye out for this.

**Comment by mirw** [comment] 2017-02-06 16:19
Thanks!  Yes, the logs look like the previous issue - specifically, ralf was not running when we reloaded the monit daemon, which triggered the previous (broken) behavior.

**Comment by rkd-msw** [comment] 2017-02-24 10:30
Duplicate of https://github.com/Metaswitch/clearwater-etcd/issues/384, which is now closed.

**Closed by rkd-msw** 2017-02-24 10:30 UTC
Labels: cat:diagnostics, cat:system-test, high-priority, major
