### ISSUE TITLE
clearwater-monit not running after a reboot

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-monit#18] opened 2015-06-11 11:32 UTC
Sporadically, clearwater-monit is not running after a reboot. This sometimes prevents clearwater processes from starting, since some initially fail and rely on monit for a restart. 

The logs look like:
```
kernel: [   19.042091] init: clearwater-monit main process (2460) killed by HUP signal
kernel: [   19.042106] init: clearwater-monit main process ended, respawning
```
Yet clearwater-monit was not re-spawned.

I've done some investigation and have found this Ubuntu bug thread that sounds suspiciously similar - http://ubuntu-bugs.narkive.com/swLa01tj/bug-1332131-re-avahi-cups-reload-upstart-job-leads-to-weird-race-conditions.

**Comment by JimBunch** [comment] 2015-06-12 19:23
This problem is happening approximately 10% of the time and Clearwater processes may not get restarted so this issue needs to be high priority.

**Comment by mirw** [comment] 2015-06-12 23:19
@eleanor-merry, please can you take a look?

**Comment by rkd-msw** [comment] 2015-06-15 09:39
As discussed, I'm picking this up.

**Comment by rkd-msw** [comment] 2015-06-15 09:43
Doug, there are no diags uploaded for this - can you provide a diagnostics bundle from an affected system?

**Comment by rkd-msw** [comment] 2015-06-15 11:22
OK, initial investigations:

* I'm not sure https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1332131 is related - part of the issue seems to be specifically with the CUPS script ("the post-start script in the CUPS job determined CUPS wasn't running, and exited 0...which Upstart interpreted as success") rather than general Upstart infrastructure issues
* I've restarted a Project Clearwater node (running the latest code on 12.04) ten times, a Clearwater Core node (running CCv6 on Ubuntu 14.04) 30 times, and run `kill -9` on the monit process on both. After each restart and each kill -9, `sudo service clearwater-monit status` always reported `clearwater-monit start/running, process PID`. In other words, I haven't been able to reproduce this locally.
* `clearwater-monit.upstart` last changed on December 1st - https://github.com/Metaswitch/clearwater-monit/blob/master/debian/clearwater-monit.upstart. So I'd be surprised if this was a recent regression - though I can see that introducing OVAs might make restarts more frequently, and so make this more frequently hit.

Doug, some more questions for you:
* If this is being hit 10% of the time, is there any pattern to those cases? For example, do you see it significantly more frequently on Sprout nodes?
* Would you have noticed this in an earlier release, or have you started rebooting more frequently now (e.g. for OVAs)? If this definitely didn't reproduce in earlier versions, can you narrow down when it started happening?
* Does running 'service clearwater-monit start' resolve the problem, or is there something more fundamentally broken?

**Comment by dtheobald** [comment] 2015-06-15 11:37
When I was looking at this I added a post-start script to clearwater-monit's upstart script and made syslog entries at the beginning of that script and when monit was listening on its port. The problem always occurred when monit was sent a SIGHUP prior to it listening on its port (i.e. it was still starting up).

I hadn't noticed this until I started testing OVAs for which I spend and inordinate amount of time booting.

When it gets in that state a 'start clearwater-monit' does not clear the problem because upstart seems to be confused about its state; though I can clear the problem if I don't use upstart.

**Comment by rkd-msw** [comment] 2015-06-15 12:21
Thanks - if you upload diagnostics containing those syslogs, can you also point me at a branch of clearwater-monit that generates them (so I can cross-reference the log messages and potentially build that branch myself)?

**Comment by dtheobald** [comment] 2015-06-15 12:26
The next time I see it I'll capture the diags and upload them. All V7 software is on branch CC_7.0.0-WIP.

**Comment by rkd-msw** [comment] 2015-06-15 12:29
I don't see the post-start script you mention in https://github.com/ClearwaterCore/clearwater-monit/blob/CC_7.0.0-WIP/debian/clearwater-monit.upstart - can you check?

**Comment by dtheobald** [comment] 2015-06-15 12:46
I only had that in the script temporarily, so it was never checked in, but it went like this:
```
post-start script
    set +e
    logger "clearwater-monit start"
    . /etc/clearwater/config
    netstat -na | grep "LISTEN" | awk '{ print $4 }' | grep -q ":2812\$"
    while [ $? -ne 0 ]; do
        sleep 1
        netstat -na | grep "LISTEN" | awk '{ print $4 }' | grep -q ":2812\$"
    done
    logger "clearwater-monit started"
end script
```

**Comment by dtheobald** [comment] 2015-06-15 13:43
This morning I've tried to reproduce this by continually rebooting a node, but haven't had any luck. Unfortunately, that's how it seems to go (i.e. it seems to come in spurts; which is probably some kind of clue). The 10% number quoted by Jim was just a guess. I told him that I see it maybe once a day and then guessed at how many times I boot nodes in any given day.

**Comment by rkd-msw** [comment] 2015-06-15 13:59
I've added a `sleep(10);` as the first line of monit's main() function, to exacerbate any race conditions, and I'm reproducing it reliably. I'm seeing `status clearwater-monit` report start/running without a PID, but no corresponding process - does this match what you saw?

```
[homer-1]ubuntu@ec2-54-227-6-112:~$ sudo status clearwater-monit
clearwater-monit start/running
[homer-1]ubuntu@ec2-54-227-6-112:~$ pgrep -lf monit
888 /bin/bash /usr/share/clearwater/bin/clearwater_diags_monitor
[homer-1]ubuntu@ec2-54-227-6-112:~$
```

**Comment by dtheobald** [comment] 2015-06-15 14:05
Yes, and you shouldn't be able to use any upstart commands to recover.

**Comment by rkd-msw** [comment] 2015-06-15 14:36
#19 should fix this - are you OK to merge that in?

**Comment by rkd-msw** [comment] 2015-06-15 14:48
(This was automatically closed when I merged #19, but I've reopened until you can confirm it's fixed.)

**Comment by dtheobald** [comment] 2015-06-15 14:53
Yes, I'll pickup your change

**Comment by eleanor-merry** [comment] 2015-08-05 17:53
Confirmed fixed by @dtheobald

**Closed by eleanor-merry** 2015-08-05 17:53 UTC
Labels: high-priority
